### ISSUE TITLE
Lapply would save you some coding instead of the for loop

### ISSUE THREAD

**Issue by goergen95** [GeoMOER-Students-Space/mpg-envinfosys-teams-2018-rs_18_mcfest#2]
https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-rs_18_mcfest/blob/2326508c2e2cd31dbba5e97734014fe84e9fc4c6/doc/assignment_02.rmd#L26

**Comment by eikeschott** [comment]
Same is true here. Would make one line of code instead of four

**Comment by eikeschott** [comment]
edited
