### ISSUE TITLE
Too many variables

### ISSUE THREAD

**Issue by goergen95** [GeoMOER-Students-Space/mpg-envinfosys-teams-2018-rs_18_mcfest#3]
Instead of using two different variables you could write the crs-code directly in v with indexing it like:

v[c] <- crs(c)
maybe you would also have to change the for-call by make i iterating 1:length(imageList)
then it would look like

v[i] <- crs(imageList[[i]])

would still prevent using two variables for the task...

https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-rs_18_mcfest/blob/2326508c2e2cd31dbba5e97734014fe84e9fc4c6/doc/assignment_02.rmd#L37

**Comment by eikeschott** [comment]
You're right!
It would save a couple lines of code

**Comment by eikeschott** [comment]
solved and edited
