### ISSUE TITLE
Good idea!

### ISSUE THREAD

**Issue by goergen95** [GeoMOER-Students-Space/mpg-envinfosys-teams-2018-rs_18_mcfest#5]
I really liked you included some transparency to the shapefile-layer.
Really looks good in the plot 👍 

https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-rs_18_mcfest/blob/2326508c2e2cd31dbba5e97734014fe84e9fc4c6/doc/assignment_02.rmd#L88

**Comment by eikeschott** [comment]
Thanks ;)
