### ISSUE TITLE
Same index calculated twice

### ISSUE THREAD

**Issue by goergen95** [GeoMOER-Students-Space/mpg-envinfosys-teams-2018-rs_18_mcfest#6]
In line 38 and line 52 you calculate the same index under different names. Is that on purpose?

https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-rs_18_mcfest/blob/7c077aeaf116de075f834da5e6aa94c1a01a8e32/src/002_functions.R#L38

https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-rs_18_mcfest/blob/7c077aeaf116de075f834da5e6aa94c1a01a8e32/src/002_functions.R#L52

**Comment by eikeschott** [comment]
Thanks for looking through it.
That's on purpose yeah. It's just a dump with indices we found.
