### ISSUE TITLE
You are subsetting cell values not layers here

### ISSUE THREAD

**Issue by goergen95** [GeoMOER-Students-Space/mpg-envinfosys-teams-2018-rs_18_mcfest#7]
If you use only one par of [ ] you are referring to cell values. If you want to access layers please use double [[ ]]  :)

https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-rs_18_mcfest/blob/7c077aeaf116de075f834da5e6aa94c1a01a8e32/src/003_indices.R#L10

**Comment by eikeschott** [comment]
Good spot. Thanks
